FROM python:3.7-slim-stretch
COPY . .
ENV PYTHONUNBUFFERED=1
RUN pip install -r requirements.txt 
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y apt-utils
RUN apt-get install sqlite3 libsqlite3-dev -y
RUN python3 csv_to_db.py
ENV TEAM_NAME=CC_1492_1730_1767_1867
ENV workerUniqueId=0
ENTRYPOINT bash start.sh